// Generated by purs bundle 0.14.0
var PS = {};
(function(exports) {
  "use strict";

  exports.unit = {};
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function($PS) {
  // Generated by purs version 0.14.0
  "use strict";
  $PS["Data.Unit"] = $PS["Data.Unit"] || {};
  var exports = $PS["Data.Unit"];
  var $foreign = $PS["Data.Unit"];
  exports["unit"] = $foreign.unit;
})(PS);
(function(exports) {
  "use strict";      
  exports.log = msg => () => log(msg)
})(PS["GJS"] = PS["GJS"] || {});
(function($PS) {
  // Generated by purs version 0.14.0
  "use strict";
  $PS["GJS"] = $PS["GJS"] || {};
  var exports = $PS["GJS"];
  var $foreign = $PS["GJS"];
  exports["log"] = $foreign.log;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.0
  "use strict";
  $PS["Demo"] = $PS["Demo"] || {};
  var exports = $PS["Demo"];
  var Data_Unit = $PS["Data.Unit"];
  var GJS = $PS["GJS"];                
  var extension = (function () {
      var enable = function __do() {
          GJS.log("enable called")();
          return Data_Unit.unit;
      };
      var disable = function (env) {
          return function __do() {
              GJS.log("disable called")();
              return Data_Unit.unit;
          };
      };
      return {
          enable: enable,
          disable: disable
      };
  })();
  exports["extension"] = extension;
})(PS);

// necessary footer to transform a spago build into a valid gnome extension
let DemoEnv = null;
function init() {}
function enable() { DemoEnv = PS["Demo"]["extension"].enable(); }
function disable() { PS["Demo"]["extension"].disable(DemoEnv)(); }
